[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
counter = "5i6SHfXHgKsHBGUoR2mVhrDK8fo7qJ3ozzCkzfxtz2FH"

[programs.devnet]
counter = "5i6SHfXHgKsHBGUoR2mVhrDK8fo7qJ3ozzCkzfxtz2FH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/amalkm/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
